apiVersion: apps/v1
kind: Deployment
metadata:
  name: obligatorio-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obligatorio-devops
  template:
    metadata:
      labels:
        app: obligatorio-devops
    spec:
      containers:
        - name: obligatorio-devops
          image: obligatorio-devops:latest  
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
